// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_validator_collators`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-10-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `36ebd14f540e`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/people-westend-runtime/people_westend_runtime.wasm
// --pallet=pallet_validator_collators
// --header=/__w/polkadot-sdk/polkadot-sdk/cumulus/file_header.txt
// --output=./cumulus/parachains/runtimes/people/people-westend/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_validator_collators`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_validator_collators::WeightInfo for WeightInfo<T> {
	/// Storage: `ValidatorCollators::ValidatorSet` (r:1 w:1)
	/// Proof: `ValidatorCollators::ValidatorSet` (`max_values`: Some(1), `max_size`: Some(32006), added: 32501, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorCollators::PendingRotation` (r:0 w:1)
	/// Proof: `ValidatorCollators::PendingRotation` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1000]`.
	fn set_validators(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32059`
		//  Estimated: `33491`
		// Minimum execution time: 64_423_000 picoseconds.
		Weight::from_parts(67_540_578, 0)
			.saturating_add(Weight::from_parts(0, 33491))
			// Standard Error: 51
			.saturating_add(Weight::from_parts(17_769, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ValidatorCollators::ValidatorSet` (r:1 w:0)
	/// Proof: `ValidatorCollators::ValidatorSet` (`max_values`: Some(1), `max_size`: Some(32006), added: 32501, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorCollators::MaxCollators` (r:0 w:1)
	/// Proof: `ValidatorCollators::MaxCollators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorCollators::PendingRotation` (r:0 w:1)
	/// Proof: `ValidatorCollators::PendingRotation` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorCollators::Collators` (r:0 w:1)
	/// Proof: `ValidatorCollators::Collators` (`max_values`: Some(1), `max_size`: Some(32006), added: 32501, mode: `MaxEncodedLen`)
	fn set_max_collators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `33491`
		// Minimum execution time: 10_294_000 picoseconds.
		Weight::from_parts(11_366_000, 0)
			.saturating_add(Weight::from_parts(0, 33491))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `ValidatorCollators::EpochRandomness` (r:1 w:1)
	/// Proof: `ValidatorCollators::EpochRandomness` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn on_relay_state_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 4_372_000 picoseconds.
		Weight::from_parts(4_804_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
