[package]
name = "polkadot-subsystem-test-sim"
version = "0.1.0"
description = "Subsystem-agnostic deterministic simulator for testing Polkadot subsystems."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
codec = { features = ["std"], workspace = true, default-features = true }
futures = { workspace = true }
polkadot-node-clock = { workspace = true, features = ["test"], default-features = true }
polkadot-node-network-protocol.workspace = true
polkadot-node-network-protocol.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-test-helpers.workspace = true
polkadot-overseer.workspace = true
polkadot-overseer.default-features = true
polkadot-primitives = { workspace = true, features = ["test"], default-features = true }
polkadot-primitives-test-helpers.workspace = true
sc-network.workspace = true
sc-network.default-features = true
sc-network-types.workspace = true
sc-network-types.default-features = true
sp-consensus-babe.workspace = true
sp-consensus-babe.default-features = true
sp-consensus-slots.workspace = true
sp-consensus-slots.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-keyring.workspace = true
sp-keyring.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
